### ISSUE TITLE
Some Themeforest soft rejection due to this

### ISSUE THREAD

**Issue by Ataurr** [ThemeFuse/Theme-Includes#1]
Don’t use: dirname(FILE), basename( FILE ) or anything else not listed above.
= **Directory path should be get_template_directory() and not dirname( FILE ).**

= **Please remove a wildcard when including files like this:**
- http://envato.d.pr/1ixOP/2LT9AH8H
- http://envato.d.pr/14CwR/43h2UG2z

Autoloading in general is not the best practice.

**Comment by danyj** [comment]
So what about all these? 
https://themeforest.net/search?utf8=%E2%9C%93&term=unyson&referrer=homepage

they used same script

**Comment by Ataurr** [comment]
We used same script before in our theme. but New theme _emiluzelac_ soft rejected due to this issue.

**Comment by ghost** [comment]
> Don’t use: dirname(FILE)

Why?

It is not a template that must have the possibility to be overwritten in child theme, it's an internal included file.

**Comment by Ataurr** [comment]
Our theme rejected several times for this issue by this reviewer https://themeforest.net/user/emiluzelac. 

> - [ ] . Directory path should be get_template_directory() and not dirname( FILE ).
> - [ ] . Please use get_template_directory when including/requiring files.

**Comment by danyj** [comment]
Emil is head reviewer.  @Ataurr , reply back with link to this and lets see what he says.

**Comment by Ataurr** [comment]
@danyj I know he is  now head reviewer. also he was reviewer admin in wordpress.org theme review team.

**Comment by ghost** [comment]
1. Theme Includes can be placed in any directory
   
   ```
   {theme}/inc/
   {theme}/some/deep/directory/
   ```
   
   and it will work fine because `dirname(__FILE__)` picks current directory and includes all the required sub-files/directories based on it.
   1. [code](https://github.com/ThemeFuse/Theme-Includes/blob/414cb76afa5ca0fca7de620385f4d698f9a21362/init.php#L88)
   2. [code](https://github.com/ThemeFuse/Theme-Includes/blob/414cb76afa5ca0fca7de620385f4d698f9a21362/init.php#L49)
2. [`glob('.../*.php')`](https://github.com/ThemeFuse/Theme-Includes/blob/414cb76afa5ca0fca7de620385f4d698f9a21362/init.php#L66) is used to include all `.php` files withing the `includes/` directory.
   - How else should we do that inclusion?
   - Or we should remove completely the `includes/` directory?

**Comment by danyj** [comment]
@Ataurr , reply back to the ticket, 

@moldcraft skype me bud

**Comment by Ataurr** [comment]
Here we have used two way
![Image](https://puu.sh/rjJRV/e9061f8d52.png)

Another way
 ![prefer](https://puu.sh/rjK2T/8831f88096.png) 

**Rel path can be define in top** so no need to change from middle code

**Comment by moldcraft** [comment]
@danyj I remember you reached an agreement with TF review about this, so close this issue.

**Comment by Ataurr** [comment]
@danyj  what is that ?

**Comment by danyj** [comment]
@Ataurr   can you share your include?

**Comment by Ataurr** [comment]
Just modify glob with the array. 

```
class MYTHEME_Theme_Includes
{
	private static $rel_path = null;

	private static $include_isolated_callable;

	private static $initialized = false;

	public static function init()
	{
		if (self::$initialized) {
			return;
		} else {
			self::$initialized = true;
		}

		/**
		 * Include a file isolated, to not have access to current context variables
		 */
		self::$include_isolated_callable = create_function('$path', 'include $path;');

		/**
		 * Both frontend and backend
		 */
		{
			self::include_child_first('/hooks.php');
			self::include_all_child_first('/includes');

			add_action('init', array(__CLASS__, '_action_init'));
			add_action('widgets_init', array(__CLASS__, '_action_widgets_init'));
		}

		/**
		 * Only frontend
		 */
		if (!is_admin()) {
			add_action('wp_enqueue_scripts', array(__CLASS__, '_action_enqueue_scripts'),
				20 // Include later to be able to make wp_dequeue_style|script()
			);
		}
	}

	private static function get_rel_path($append = '')
	{
		if (self::$rel_path === null) {
			self::$rel_path = '/inc';
		}

		return self::$rel_path . $append;
	}

	private static function include_all_child_first($dir_rel_path)
	{
		$paths = array();
		$files = array(
    			'class-tgm-plugin-activation.php',
    			'comment-list.php',
    			'helpers.php',
    			'img-resizer.php',
    			'menus.php',
    			'template-tags.php'		
			);

		$paths[] = self::get_parent_path($dir_rel_path);

		foreach ($paths as $path) {
			foreach ($files as $file) {
				self::include_isolated($path . '/' . $file);
			}
		}
	}

	/**
	 * @param string $dirname 'foo-bar'
	 * @return string 'Foo_Bar'
	 */
	private static function dirname_to_classname($dirname) {
		$class_name = explode('-', $dirname);
		$class_name = array_map('ucfirst', $class_name);
		$class_name = implode('_', $class_name);

		return $class_name;
	}

	public static function get_parent_path($rel_path)
	{
		return get_template_directory() . self::get_rel_path($rel_path);
	}

	public static function get_child_path($rel_path)
	{
		if (!is_child_theme()) {
			return null;
		}

		return get_stylesheet_directory() . self::get_rel_path($rel_path);
	}

	public static function include_isolated($path)
	{
		call_user_func(self::$include_isolated_callable, $path);
	}

	public static function include_child_first($rel_path)
	{
		if (is_child_theme()) {
			$path = self::get_child_path($rel_path);

			if (file_exists($path)) {
				self::include_isolated($path);
			}
		}

		{
			$path = self::get_parent_path($rel_path);

			if (file_exists($path)) {
				self::include_isolated($path);
			}
		}
	}

	/**
	 * @internal
	 */
	public static function _action_enqueue_scripts()
	{
		self::include_child_first('/enqueue-static.php');
		self::include_child_first('/enqueue-inline.php');
	}

	/**
	 * @internal
	 */
	public static function _action_init()
	{
		self::include_child_first('/menus.php');
	}

	/**
	 * @internal
	 */
	public static function _action_widgets_init()
	{
		{
			$paths = array();

			if (is_child_theme()) {
				$paths[] = self::get_child_path('/widgets');
			}

			$paths[] = self::get_parent_path('/widgets');
		}

		$included_widgets = array();

		foreach ($paths as $path) {
			$dirs = glob($path .'/*', GLOB_ONLYDIR);

			if (!$dirs) {
				continue;
			}

			foreach ($dirs as $dir) {
				$dirname = basename($dir);

				if (isset($included_widgets[$dirname])) {
					// this happens when a widget in child theme wants to overwrite the widget from parent theme
					continue;
				} else {
					$included_widgets[$dirname] = true;
				}

				self::include_isolated($dir .'/class-widget-'. $dirname .'.php');

				$widget_class = 'Widget_' . self::dirname_to_classname( $dirname );
				if ( class_exists( $widget_class ) ) {
					register_widget( $widget_class );
				}

			}
		}
	}
}
MYTHEME_Theme_Includes::init();
```

**Comment by danyj** [comment]
yes , but the foreach path is not needed there and the substituting array takes away the main reason for the method wich was to include any file that is dropped in includes folder . I also understand why Emil does not like this since any file dropped or uploaded ( hack ) there  will be included in the theme ,  so I made own modification that will somewhat still help users that have child activated and need to include files , plus it will restrict what files are included , 



	private static function get_includes_files_list($dir_rel_path){
		
		
		$path  	= self::get_parent_path($dir_rel_path). '/'; 
		
		$includes_files_list = array(
			
			$path.'some-file-in-include-folder.php'
		);	
		
		$custom_list =  apply_filters ('my_theme_filter_init_includes_custom_files',array());
		
		if(!empty($custom_list)){
			
			$prefixed_files = array();
			$child_path = self::get_child_path($dir_rel_path). '/';
			
			foreach ($custom_list as $file) {
				$prefixed_files[] = $child_path . $file;
			}	
					
			unset($custom_list);
			
			$includes_files_list = array_merge($includes_files_list, $prefixed_files);	
			
			unset($prefixed_files);
		}
		
		return $includes_files_list;
	}
	
	
	
	
	private static function get_rel_path($append = '')
	{
		if (self::$rel_path === null) {
			self::$rel_path = '/inc';
		}

		return self::$rel_path . $append;
	}

	private static function include_all_child_first($dir_rel_path)
	{

		$files 	= self::get_includes_files_list($dir_rel_path);
		
		foreach ($files as $file) {

			if(file_exists( $file )){
				
				self::include_isolated( $file );
				
			}
		}
		unset($files);
	}


now in child functions.php you can do this


```
// include files from child includes folder
//place files in themename-child/inc/includes  folder 

function my_filter_include_files ( $custom_list ){
    $custom_list[]='my-includes-custom-file.php';
    return $custom_list;
}

add_filter('my_theme_filter_init_includes_custom_files', 'my_filter_include_files' );
```
