### ISSUE TITLE
Deprecated: Function create_function() is deprecated in \inc\init.php on line 22

### ISSUE THREAD

**Issue by Ataurr** [ThemeFuse/Theme-Includes#2]
@andreiglingeanu  @GheorgheP I have updated the php latest version 7.2 and showing this error at the top.

`Deprecated: Function create_function() is deprecated in \inc\init.php on line 22`

http://au.php.net/create_function

**Comment by ViorelEremia** [comment]
https://github.com/ThemeFuse/Scratch-Theme/commit/6ad21caa154319fe82d9f6816b74f2355154c70e
https://github.com/ThemeFuse/Scratch-Theme/commit/6e26e3f3ffa67338581fc1e63d0a5758881cca5f
